#!/bin/bash
#SBATCH -J gromacs-extrae-tiny
#SBATCH -t 04:00:00
#SBATCH -p broadwell
#SBATCH -N 2
#SBATCH -n 16
#SBATCH -c 4
module load 2019
module load foss/2018b
module load Extrae/3.6.1-foss-2018b

export GROMACSINSTALLDIR=/home/$USER/gromacs-2019.3/install
export GROMACSTESTCASEDIR=/home/$USER/gromacs_testcase
export NNODES=$SLURM_JOB_NUM_NODES
export NPROC=$SLURM_NTASKS
export NTHREADS=$SLURM_CPUS_PER_TASK
export TESTCASE=ion_channel_tiny
export INPUTFILENAME=ion_channel.tpr
export RESULTDIR=${SLURM_SUBMIT_DIR}/${SLURM_JOB_ID}_gromacs_${TESTCASE}_${NNODES}N_${NPROC}P_${NTHREADS}T_extrae-ldpreload
export WORKDIR=/scratch-shared/${USER}/${SLURM_JOB_ID}
#export FILTERFILENAME=scorep-gromacs.filt

# copy executable and input directory to workdir
mkdir -p $WORKDIR
cp ${GROMACSINSTALLDIR}/bin/gmx_mpi ${GROMACSTESTCASEDIR}/${INPUTFILENAME} ${WORKDIR}
cp ${GROMACSTESTCASEDIR}/${FILTERFILENAME} ${WORKDIR}

# Use 'default' trace.sh and extrae.xml files if TRACE_SCRIPT and EXTRAE_CONFIG_FILE were not passed as environment variables to sbatch
if [ `echo $TRACE_SCRIPT | wc -m` == 1 ]
then
  export TRACE_SCRIPT=${EBROOTEXTRAE}/share/example/MPI+OMP/ld-preload/trace.sh
fi
if [ `echo $EXTRAE_CONFIG_FILE | wc -m` == 1 ]
then
  export EXTRAE_CONFIG_FILE=${EBROOTEXTRAE}/share/example/MPI+OMP/ld-preload/extrae.xml
fi

# get the extrae configuration files and make changes to it if necessary
#cp ${EBROOTEXTRAE}/share/example/MPI+OMP/extrae.xml .
cp ${EXTRAE_CONFIG_FILE} ${WORKDIR}
cp ${TRACE_SCRIPT} ${WORKDIR}
#sed -i -e 's/..\/extrae.xml/extrae.xml/g' ${TRACE_SCRIPT}

# cd to the working directory (on scratch)
cd $WORKDIR

# set Extrae variables
#source ${EBROOTEXTRAE}/etc/extrae.sh
#export EXTRAE_CONFIG_FILE=extrae.xml
#export LD_PRELOAD=${EBROOTEXTRAE}/lib/libompitrace.so
export TRACE_NAME=${SLURM_JOB_ID}_gromacs_${TESTCASE}_${NNODES}N_${NPROC}P_${NTHREADS}T_extrae-ldpreload.prv

# print information about the job to stdout
echo "========================================================="
echo "Using gromacs executable ${GROMACSINSTALLDIR}/bin/gmx_mpi"
echo "on test case ${TESTCASE} (input file ${INPUTFILENAME}) located in ${GROMACSTESTCASEDIR}"
echo "The test will run in ${WORKDIR}"
echo "and the output will be copied to ${RESULTDIR}"
echo "========================================================="
echo "Running testcase ${TESTCASE} on ${NNODES} nodes / ${NPROC} MPI processes / ${NTHREADS} OpenMP threads per process"
echo "========================================================="
echo ""
# run test case
OMP_NUM_THREADS=$NTHREADS \
srun -N $NNODES -n $NPROC ./${TRACE_SCRIPT} ./gmx_mpi mdrun \
    -s ${INPUTFILENAME} -maxh 0.50 -noconfout -nsteps 1000 \
    -g ${SLURM_JOB_ID}_gromacs_${TESTCASE}_${NNODES}N_${NPROC}P_${NTHREADS}T_extrae-ldpreload.log \
&> ${SLURM_JOB_ID}_stdouterr_gromacs_${TESTCASE}_${NNODES}N_${NPROC}P_${NTHREADS}T_extrae-ldpreload.log
#    -s ${INPUTFILENAME} -maxh 0.50 -resethway -noconfout -nsteps 10000 \

# copy back results to home directory
mkdir ${RESULTDIR}
cp -r ${SLURM_JOB_ID}_* *.prv *.row *.pcf  ${RESULTDIR}
