#!/bin/bash
#SBATCH -J gromacs-extrae-tiny
#SBATCH -t 04:00:00
#SBATCH -p broadwell
#SBATCH -N 2
#SBATCH -n 16
#SBATCH -c 4
module load 2019
module load foss/2018b
module load Extrae/3.6.1-foss-2018b

export GROMACSINSTALLDIR=/home/$USER/gromacs-2019.3/install
export GROMACSTESTCASEDIR=/home/$USER/gromacs_testcase
export NNODES=$SLURM_JOB_NUM_NODES
export NPROC=$SLURM_NTASKS
export NTHREADS=$SLURM_CPUS_PER_TASK
export TESTCASE=ion_channel_tiny
export INPUTFILENAME=ion_channel.tpr
export RESULTDIR=${SLURM_SUBMIT_DIR}/${SLURM_JOB_ID}_gromacs_${TESTCASE}_${NNODES}N_${NPROC}P_${NTHREADS}T_extrae-ldpreload
export WORKDIR=/scratch-shared/${USER}/${SLURM_JOB_ID}
#export FILTERFILENAME=scorep-gromacs.filt

# copy executable and input directory to workdir
mkdir -p $WORKDIR
cp ${GROMACSINSTALLDIR}/bin/gmx_mpi ${GROMACSTESTCASEDIR}/${INPUTFILENAME} ${WORKDIR}
cp ${GROMACSTESTCASEDIR}/${FILTERFILENAME} ${WORKDIR}
cd $WORKDIR

# get the extrae configuration files and make changes to it if necessary
#cp ${EBROOTEXTRAE}/share/example/MPI+OMP/extrae.xml .
cp ${GROMACSTESTCASEDIR}/extrae-cfgs/extrae_papi-counters.xml extrae.xml
cp ${EBROOTEXTRAE}/share/example/MPI+OMP/ld-preload/trace.sh .
sed -i -e 's/..\/extrae.xml/extrae.xml/g' trace.sh
# sed -i 's/PAPI_TOT_INS,PAPI_TOT_CYC,PAPI_L1_DCM,PAPI_L2_DCM,PAPI_L3_TCM,PAPI_BR_INS,PAPI_BR_MSP,RESOURCE_STALLS/PAPI_TOT_INS,PAPI_TOT_CYC,PAPI_REF_CYC,PAPI_SP_OPS,PAPI_DP_OPS,PAPI_VEC_SP,PAPI_VEC_DP,PAPI_L1_TCM,PAPI_L2_TCM,PAPI_L1_DCM,PAPI_L2_DCM,PAPI_L3_TCM,,PAPI_BR_INS,PAPI_BR_MSP,RESOURCE_STALLS,PAPI_LD_INS,PAPI_SR_INS,PAPI_LST_INS,PAPI_RES_STL,PAPI_L1_TCM,PAPI_L2_TCM,PAPI_L1_DCM,PAPI_L2_DCM,PAPI_L2_DCA,PAPI_L3_DCA,PAPI_LD_INS,PAPI_SR_INS,PAPI_LST_INS/g' extrae.xml


# set Extrae variables
#source ${EBROOTEXTRAE}/etc/extrae.sh
#export EXTRAE_CONFIG_FILE=extrae.xml
#export LD_PRELOAD=${EBROOTEXTRAE}/lib/libompitrace.so
export TRACE_NAME=${SLURM_JOB_ID}_gromacs_${TESTCASE}_${NNODES}N_${NPROC}P_${NTHREADS}T_extrae-ldpreload.prv

# print information about the job to stdout
echo "========================================================="
echo "Using gromacs executable ${GROMACSINSTALLDIR}/bin/gmx_mpi"
echo "on test case ${TESTCASE} (input file ${INPUTFILENAME}) located in ${GROMACSTESTCASEDIR}"
echo "The test will run in ${WORKDIR}"
echo "and the output will be copied to ${RESULTDIR}"
echo "========================================================="
echo "Running testcase ${TESTCASE} on ${NNODES} nodes / ${NPROC} MPI processes / ${NTHREADS} OpenMP threads per process"
echo "========================================================="
echo ""
# run test case
OMP_NUM_THREADS=$NTHREADS \
srun -N $NNODES -n $NPROC ./trace.sh ./gmx_mpi mdrun \
    -s ${INPUTFILENAME} -maxh 0.50 -noconfout -nsteps 1000 \
    -g ${SLURM_JOB_ID}_gromacs_${TESTCASE}_${NNODES}N_${NPROC}P_${NTHREADS}T_extrae-ldpreload.log \
&> ${SLURM_JOB_ID}_stdouterr_gromacs_${TESTCASE}_${NNODES}N_${NPROC}P_${NTHREADS}T_extrae-ldpreload.log
#    -s ${INPUTFILENAME} -maxh 0.50 -resethway -noconfout -nsteps 10000 \

# copy back results to home directory
mkdir ${RESULTDIR}
cp -r ${SLURM_JOB_ID}_* *.prv *.row *.pcf  ${RESULTDIR}
